-- ═══════════════════════════════════════════════════════════════════════════════
--  GrantFlow Proposer — Initial Migration
--  001_init_grantflow_proposer.sql
-- ═══════════════════════════════════════════════════════════════════════════════
--
--  Creates all tables for the grantflow-proposer service and pre-seeds the
--  7 default section templates.
--
--  Tables:
--    gf_proposals   — grant proposal documents (linked to grantflow-discovery submissions)
--    gf_sections    — individual proposal sections with version tracking
--    gf_templates   — reusable section templates (7 defaults pre-seeded)
--    gf_refinements — AI refinement passes with quality delta tracking
--    gf_claims      — local claim records (mirrors Epistemology Engine entries)
--
-- ═══════════════════════════════════════════════════════════════════════════════

BEGIN;

-- ── Core Tables ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gf_proposals (
  id                    UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  submission_id         TEXT        NOT NULL,
  opportunity_title     TEXT        NOT NULL,
  agency                TEXT        NOT NULL,
  opportunity_number    TEXT,
  principal_investigator TEXT,
  requested_amount      NUMERIC(14, 2),
  proposal_duration     TEXT,
  status                TEXT        NOT NULL DEFAULT 'draft'
                          CHECK (status IN ('draft', 'generating', 'complete', 'exported')),
  quality_score         NUMERIC(5, 2) NOT NULL DEFAULT 0
                          CHECK (quality_score >= 0 AND quality_score <= 100),
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  gf_proposals IS 'Grant proposal documents, each linked to a grantflow-discovery submission.';
COMMENT ON COLUMN gf_proposals.submission_id IS 'References gf_submissions.id in the grantflow-discovery service.';
COMMENT ON COLUMN gf_proposals.quality_score IS 'Composite quality score (0–100), arithmetic mean of section quality scores.';
COMMENT ON COLUMN gf_proposals.status IS 'Lifecycle: draft → generating → complete → exported.';

CREATE INDEX IF NOT EXISTS idx_gf_proposals_submission_id ON gf_proposals(submission_id);
CREATE INDEX IF NOT EXISTS idx_gf_proposals_status        ON gf_proposals(status);
CREATE INDEX IF NOT EXISTS idx_gf_proposals_agency        ON gf_proposals(LOWER(agency));
CREATE INDEX IF NOT EXISTS idx_gf_proposals_created_at    ON gf_proposals(created_at DESC);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gf_sections (
  id               UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id      UUID        NOT NULL REFERENCES gf_proposals(id) ON DELETE CASCADE,
  section_type     TEXT        NOT NULL
                     CHECK (section_type IN (
                       'EXECUTIVE_SUMMARY', 'PROJECT_NARRATIVE', 'BUDGET_JUSTIFICATION',
                       'EVALUATION_PLAN', 'ORGANIZATIONAL_CAPACITY', 'LETTERS_OF_SUPPORT', 'REFERENCES'
                     )),
  content          TEXT        NOT NULL DEFAULT '',
  version          INTEGER     NOT NULL DEFAULT 1 CHECK (version >= 1),
  quality_score    NUMERIC(5, 2) NOT NULL DEFAULT 0
                     CHECK (quality_score >= 0 AND quality_score <= 100),
  is_ai_generated  BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- Each proposal should have at most one section of each type
  UNIQUE (proposal_id, section_type)
);

COMMENT ON TABLE  gf_sections IS 'Individual proposal sections with version tracking.';
COMMENT ON COLUMN gf_sections.version IS 'Incremented on each content update — provides implicit audit trail.';
COMMENT ON COLUMN gf_sections.is_ai_generated IS 'TRUE if generated by OpenAI/template engine; FALSE if manually written.';

CREATE INDEX IF NOT EXISTS idx_gf_sections_proposal_id ON gf_sections(proposal_id);
CREATE INDEX IF NOT EXISTS idx_gf_sections_type        ON gf_sections(section_type);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gf_templates (
  id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  name         TEXT        NOT NULL,
  section_type TEXT        NOT NULL
                 CHECK (section_type IN (
                   'EXECUTIVE_SUMMARY', 'PROJECT_NARRATIVE', 'BUDGET_JUSTIFICATION',
                   'EVALUATION_PLAN', 'ORGANIZATIONAL_CAPACITY', 'LETTERS_OF_SUPPORT', 'REFERENCES'
                 )),
  content      TEXT        NOT NULL,
  is_default   BOOLEAN     NOT NULL DEFAULT FALSE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  gf_templates IS 'Reusable section templates with {placeholder} variable syntax.';
COMMENT ON COLUMN gf_templates.is_default IS 'Each section type should have at most one default template.';

CREATE INDEX IF NOT EXISTS idx_gf_templates_section_type ON gf_templates(section_type);
CREATE INDEX IF NOT EXISTS idx_gf_templates_is_default   ON gf_templates(section_type, is_default);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gf_refinements (
  id              UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  proposal_id     UUID        NOT NULL REFERENCES gf_proposals(id) ON DELETE CASCADE,
  section_id      UUID        NOT NULL REFERENCES gf_sections(id)  ON DELETE CASCADE,
  before_content  TEXT        NOT NULL,
  after_content   TEXT        NOT NULL,
  quality_delta   NUMERIC(5, 2) NOT NULL DEFAULT 0,
  instructions    TEXT        NOT NULL DEFAULT '',
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  gf_refinements IS 'Refinement passes — tracks before/after content and quality delta per iteration.';
COMMENT ON COLUMN gf_refinements.quality_delta IS 'Positive = quality improved; negative = quality degraded.';

CREATE INDEX IF NOT EXISTS idx_gf_refinements_proposal_id ON gf_refinements(proposal_id);
CREATE INDEX IF NOT EXISTS idx_gf_refinements_section_id  ON gf_refinements(section_id);

-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS gf_claims (
  id          BIGSERIAL   PRIMARY KEY,
  claim_id    TEXT        NOT NULL UNIQUE,
  loop_id     TEXT        NOT NULL,
  proposal_id TEXT        NOT NULL,
  claim_type  TEXT        NOT NULL,
  statement   TEXT        NOT NULL,
  domain      TEXT        NOT NULL,
  status      TEXT        NOT NULL DEFAULT 'submitted',
  xp_value    NUMERIC(10, 4),
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE  gf_claims IS 'Local claim records mirroring entries in the Epistemology Engine.';
COMMENT ON COLUMN gf_claims.claim_id IS 'UUID assigned by the Epistemology Engine (or locally generated if engine unreachable).';
COMMENT ON COLUMN gf_claims.loop_id  IS 'Loop ID for tracking claim lifecycle through the Extropy Engine.';
COMMENT ON COLUMN gf_claims.status   IS 'submitted → verified/falsified → xp_minted';

CREATE INDEX IF NOT EXISTS idx_gf_claims_proposal_id ON gf_claims(proposal_id);
CREATE INDEX IF NOT EXISTS idx_gf_claims_loop_id     ON gf_claims(loop_id);
CREATE INDEX IF NOT EXISTS idx_gf_claims_status      ON gf_claims(status);

-- ── Shared Event Log ──────────────────────────────────────────────────────────
-- Ensures the shared event_log table exists (other services may have created it)

CREATE TABLE IF NOT EXISTS public.event_log (
  id             BIGSERIAL   PRIMARY KEY,
  event_id       TEXT        NOT NULL UNIQUE,
  type           TEXT        NOT NULL,
  payload        JSONB       NOT NULL,
  source         TEXT        NOT NULL,
  correlation_id TEXT        NOT NULL,
  version        INTEGER     NOT NULL DEFAULT 1,
  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_log_type           ON public.event_log(type);
CREATE INDEX IF NOT EXISTS idx_event_log_correlation_id ON public.event_log(correlation_id);
CREATE INDEX IF NOT EXISTS idx_event_log_source         ON public.event_log(source);
CREATE INDEX IF NOT EXISTS idx_event_log_created_at     ON public.event_log(created_at DESC);

-- ═══════════════════════════════════════════════════════════════════════════════
--  Pre-Seed: 7 Default Section Templates
-- ═══════════════════════════════════════════════════════════════════════════════
--
--  Each section type gets exactly one default template. Templates use
--  {placeholder} syntax — the generation service fills these in with
--  opportunity data + researcher profile data at generation time.
--
-- ═══════════════════════════════════════════════════════════════════════════════

-- Template 1: Executive Summary
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default Executive Summary',
  'EXECUTIVE_SUMMARY',
  $template$
# Executive Summary

This project proposes to {objective}. Building on {prior_work}, our team will employ {methodology} to achieve {outcomes}.

**Project Title:** {opportunity_title}
**Principal Investigator:** {principal_investigator}
**Institution:** {institution}
**Funding Agency:** {agency}
**Total Budget Requested:** {budget}
**Project Duration:** {duration}

## Problem Statement

{problem_statement}

## Proposed Solution

Our approach leverages {key_innovation} to address the fundamental challenges of {research_domain}. The proposed work will directly advance the agency's priority areas by {alignment_with_priorities}.

## Team Qualifications

Our team brings {qualifications} to this effort. The PI has {pi_experience} and has previously {prior_achievements}. The collaborative team includes expertise in {team_expertise}.

## Expected Impact

Upon completion, this project will {expected_impact}. Results will be disseminated through {dissemination_plan}.
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

-- Template 2: Project Narrative
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default Project Narrative',
  'PROJECT_NARRATIVE',
  $template$
# Project Narrative

## 1. Background and Significance

{background_significance}

The field of {research_domain} has made substantial progress in recent years, with particular advances in {recent_advances}. However, significant gaps remain in our understanding of {knowledge_gaps}. This project directly addresses these gaps by {gap_address_strategy}.

The significance of this work is supported by the following:
- {significance_point_1}
- {significance_point_2}
- {significance_point_3}

## 2. Research Objectives and Specific Aims

The long-term objective of this research is to {long_term_objective}. The specific aims of this project are:

**Aim 1:** {aim_1_title}
{aim_1_description}

**Aim 2:** {aim_2_title}
{aim_2_description}

**Aim 3:** {aim_3_title}
{aim_3_description}

## 3. Methodology

### Research Design
{research_design}

### Data Collection and Analysis
{data_collection}

### Preliminary Studies
{preliminary_studies}

### Potential Challenges and Mitigation
{challenges_mitigation}

## 4. Expected Outcomes

Upon successful completion of this project, we expect to:
1. {outcome_1}
2. {outcome_2}
3. {outcome_3}

These outcomes will be measured by {outcome_metrics}.

## 5. Timeline and Milestones

| Quarter | Milestone | Deliverable |
|---------|-----------|-------------|
| Q1–Q2   | {milestone_1} | {deliverable_1} |
| Q3–Q4   | {milestone_2} | {deliverable_2} |
| Q5–Q6   | {milestone_3} | {deliverable_3} |
| Q7–Q8   | {milestone_4} | {deliverable_4} |

## 6. Broader Impacts

This project advances scientific understanding by {scientific_contribution}. The educational activities associated with this project include {educational_activities}. The work will benefit {broader_community} through {broader_benefits}.
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

-- Template 3: Budget Justification
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default Budget Justification',
  'BUDGET_JUSTIFICATION',
  $template$
# Budget Justification

**Total Requested Budget:** {total_budget}
**Project Duration:** {duration}
**Funding Agency:** {agency}

---

## A. Personnel

### Principal Investigator — {principal_investigator}
**Effort:** {pi_effort}% | **Annual Salary:** {pi_salary} | **Total Personnel Cost:** {pi_total}

The PI will provide overall scientific leadership for this project, including {pi_responsibilities}. The PI's expertise in {pi_expertise} is essential to the success of Aims {relevant_aims}.

### Co-Investigator — {co_investigator_name}
**Effort:** {co_i_effort}% | **Annual Salary:** {co_i_salary}

{co_i_justification}

### Graduate Research Assistants (×{num_grad_students})
**Annual Stipend per Student:** {grad_stipend} | **Total:** {grad_total}

Graduate students will conduct {grad_student_duties}. Their training is integral to the educational mission of this project.

### Fringe Benefits
Personnel fringe benefits are calculated at {fringe_rate}% of salaries: **{fringe_total}**

---

## B. Equipment

| Item | Cost | Justification |
|------|------|---------------|
| {equipment_1_name} | {equipment_1_cost} | {equipment_1_justification} |
| {equipment_2_name} | {equipment_2_cost} | {equipment_2_justification} |

**Equipment Subtotal:** {equipment_total}

---

## C. Travel

### Domestic Conference Travel
**Amount:** {domestic_travel_cost}

The PI and key personnel will present findings at {target_conferences}. Conference attendance is essential for {travel_justification}.

**Travel Subtotal:** {travel_total}

---

## D. Supplies and Materials

| Category | Annual Cost | Justification |
|----------|-------------|---------------|
| {supplies_1_name} | {supplies_1_cost} | {supplies_1_justification} |

**Supplies Subtotal:** {supplies_total}

---

## E. Other Direct Costs

| Item | Cost | Justification |
|------|------|---------------|
| Publication costs | {publication_cost} | Open-access dissemination of results |

**Other Direct Costs Subtotal:** {other_direct_total}

---

## F. Indirect Costs (F&A)

Indirect costs are calculated at {indirect_rate}% of Modified Total Direct Costs (MTDC): **{indirect_total}**

The rate is based on {institution}'s federally negotiated rate agreement.

---

## Budget Summary

| Category | Year 1 | Year 2 | Year 3 | Total |
|----------|--------|--------|--------|-------|
| Personnel | {y1_personnel} | {y2_personnel} | {y3_personnel} | {total_personnel} |
| Equipment | {y1_equipment} | {y2_equipment} | {y3_equipment} | {total_equipment} |
| Travel | {y1_travel} | {y2_travel} | {y3_travel} | {total_travel} |
| Supplies | {y1_supplies} | {y2_supplies} | {y3_supplies} | {total_supplies} |
| Other Direct | {y1_other} | {y2_other} | {y3_other} | {total_other} |
| Indirect Costs | {y1_indirect} | {y2_indirect} | {y3_indirect} | {total_indirect} |
| **TOTAL** | **{y1_total}** | **{y2_total}** | **{y3_total}** | **{grand_total}** |
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

-- Template 4: Evaluation Plan
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default Evaluation Plan',
  'EVALUATION_PLAN',
  $template$
# Evaluation Plan

## 1. Evaluation Framework

This evaluation follows a {evaluation_framework_type} framework to assess both process fidelity and outcome achievement. The evaluation is designed to answer the following primary questions:

1. {evaluation_question_1}
2. {evaluation_question_2}
3. {evaluation_question_3}

## 2. Performance Metrics and Indicators

### Primary Outcome Metrics

| Metric | Baseline | Year 1 Target | Year 2 Target | Year 3 Target | Data Source |
|--------|----------|---------------|---------------|---------------|-------------|
| {metric_1_name} | {metric_1_baseline} | {metric_1_y1} | {metric_1_y2} | {metric_1_y3} | {metric_1_source} |
| {metric_2_name} | {metric_2_baseline} | {metric_2_y1} | {metric_2_y2} | {metric_2_y3} | {metric_2_source} |
| {metric_3_name} | {metric_3_baseline} | {metric_3_y1} | {metric_3_y2} | {metric_3_y3} | {metric_3_source} |

### Process Metrics

- **Activity completion rate:** {activity_completion_target}%
- **Participant engagement:** {engagement_target}
- **Timeline adherence:** {timeline_adherence_target}%

## 3. Data Collection Methods

### Quantitative Data
{quantitative_data_methods}

### Qualitative Data
{qualitative_data_methods}

### Data Quality Assurance
{data_quality_procedures}

## 4. Analysis Approach

### Statistical Methods
{statistical_methods}

### Qualitative Analysis
{qualitative_analysis_approach}

## 5. Reporting Schedule

| Report | Audience | Due Date | Contents |
|--------|----------|----------|----------|
| Quarterly Progress Report | Program Officer | {quarterly_due_dates} | Activity updates, preliminary metrics |
| Annual Performance Report | {agency} | End of each project year | Full metric reporting, narrative |
| Final Evaluation Report | {agency} + Public | 90 days post-project | Comprehensive findings, recommendations |

## 6. External Evaluator

{external_evaluator_name} of {external_evaluator_institution} will serve as the independent external evaluator. Their qualifications include {evaluator_qualifications}. The evaluator will {evaluator_responsibilities}.
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

-- Template 5: Organizational Capacity
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default Organizational Capacity',
  'ORGANIZATIONAL_CAPACITY',
  $template$
# Organizational Capacity

## 1. Institutional Overview

{institution} has a distinguished history of conducting federally funded research in {research_domains}. The institution serves {institution_description}.

### Research Enterprise
- **Annual research expenditures:** {annual_research_expenditures}
- **Active federal grants:** {active_federal_grants}
- **Sponsored programs office:** {spo_description}

## 2. Relevant Past Performance

### Representative Awards

| Grant | Agency | Period | Award Amount | PI | Outcome |
|-------|--------|--------|--------------|----|---------|
| {grant_1_title} | {grant_1_agency} | {grant_1_period} | {grant_1_amount} | {grant_1_pi} | {grant_1_outcome} |
| {grant_2_title} | {grant_2_agency} | {grant_2_period} | {grant_2_amount} | {grant_2_pi} | {grant_2_outcome} |

### Programmatic Accomplishments
{past_accomplishments}

## 3. Key Personnel and Qualifications

### {principal_investigator}, {pi_title}
{pi_bio}

**Selected Publications:**
{pi_publications}

### Co-Investigators and Senior Personnel
{co_investigator_bios}

## 4. Facilities and Resources

### Laboratory and Research Space
{laboratory_description}

### Computing and Data Infrastructure
{computing_infrastructure}

### Administrative and Support Infrastructure
{administrative_infrastructure}

## 5. Partnerships and Collaborations

{partnerships_description}

## 6. Commitment to This Project

{institution} is committed to providing the following resources to support this project:
- {institutional_resource_1}
- {institutional_resource_2}
- {institutional_resource_3}
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

-- Template 6: Letters of Support
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default Letter of Support Template',
  'LETTERS_OF_SUPPORT',
  $template$
# Letters of Support

---

{partner_name}
{partner_title}
{partner_institution}
{partner_address}

{date}

Program Officer
{agency}

**Re: Letter of Support for "{opportunity_title}" — {principal_investigator}, {institution}**

Dear Program Officer,

I am writing in strong support of the proposal submitted by {principal_investigator} at {institution} to the {agency}. As {partner_role_description}, I am uniquely positioned to attest to the significance, feasibility, and expected impact of this work.

**Significance of the Proposed Research**

{significance_statement}

**Basis for Collaboration**

Our organizations have collaborated since {collaboration_start_date} on {prior_collaboration_description}. This relationship has {collaboration_outcomes}. The proposed project represents a natural extension of this partnership.

**Specific Contributions**

Under this project, {partner_institution} will provide the following:
1. {contribution_1}
2. {contribution_2}
3. {contribution_3}

These contributions are not contingent on additional funding and represent a firm commitment from our organization.

**Anticipated Impact**

We expect that the successful completion of this project will {expected_impact_statement}. Our organization will benefit through {organizational_benefit}.

I am available to discuss this letter at your convenience and can be reached at {partner_email}.

Sincerely,

{partner_name}
{partner_title}
{partner_institution}

---

*[Additional letters of support from collaborating organizations are attached as appendices.]*
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

-- Template 7: References
INSERT INTO gf_templates (id, name, section_type, content, is_default)
VALUES (
  gen_random_uuid(),
  'Default References',
  'REFERENCES',
  $template$
# References and Preliminary Studies

## 1. Preliminary Data

### Overview of Preliminary Studies

{preliminary_overview}

### Study 1: {preliminary_study_1_title}
**Methods:** {preliminary_study_1_methods}
**Results:** {preliminary_study_1_results}
**Significance:** {preliminary_study_1_significance}

### Study 2: {preliminary_study_2_title}
**Methods:** {preliminary_study_2_methods}
**Results:** {preliminary_study_2_results}
**Significance:** {preliminary_study_2_significance}

## 2. Prior Publications Supporting This Proposal

The following publications from our lab provide the scientific foundation for this project:

1. {author_list_1} ({year_1}). {title_1}. *{journal_1}*, {volume_1}({issue_1}), {pages_1}. DOI: {doi_1}

2. {author_list_2} ({year_2}). {title_2}. *{journal_2}*, {volume_2}({issue_2}), {pages_2}. DOI: {doi_2}

3. {author_list_3} ({year_3}). {title_3}. *{journal_3}*, {volume_3}({issue_3}), {pages_3}. DOI: {doi_3}

## 3. Literature References

1. {ref_1_authors} ({ref_1_year}). {ref_1_title}. *{ref_1_journal}*, {ref_1_vol_pages}. DOI: {ref_1_doi}

2. {ref_2_authors} ({ref_2_year}). {ref_2_title}. *{ref_2_journal}*, {ref_2_vol_pages}. DOI: {ref_2_doi}

3. {ref_3_authors} ({ref_3_year}). {ref_3_title}. *{ref_3_journal}*, {ref_3_vol_pages}. DOI: {ref_3_doi}

4. {ref_4_authors} ({ref_4_year}). {ref_4_title}. *{ref_4_journal}*, {ref_4_vol_pages}. DOI: {ref_4_doi}

5. {ref_5_authors} ({ref_5_year}). {ref_5_title}. *{ref_5_journal}*, {ref_5_vol_pages}. DOI: {ref_5_doi}

---

*All references formatted per {citation_style} guidelines. Full bibliography available upon request.*
  $template$,
  TRUE
)
ON CONFLICT DO NOTHING;

COMMIT;

-- ═══════════════════════════════════════════════════════════════════════════════
--  Verification
-- ═══════════════════════════════════════════════════════════════════════════════

DO $$
DECLARE
  template_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO template_count FROM gf_templates WHERE is_default = TRUE;
  IF template_count < 7 THEN
    RAISE NOTICE 'Warning: Expected 7 default templates, found %', template_count;
  ELSE
    RAISE NOTICE 'Migration 001 complete: % default templates seeded', template_count;
  END IF;
END $$;
